### ISSUE TITLE
Your URL Shortener

### ISSUE THREAD

**Issue by ghost** [liyasthomas/mnmlurl#1]
Hi,

I liked the script, I only uploaded the src folder and it worked fine,
Should i upload the other files too ? Besides, please remove the # from the generated keyword string,
http://icu2.cf/m/

**Comment by liyasthomas** [comment]
@mtsmayad I'm glad you liked it.
Please continue to let me know if you make any changes to the code.

IMPORTANT:
Please find `var endpoint` on `head.js` file and replace it with your own endpoint which can be found here: https://www.jsonstore.io/

```var endpoint = "https://www.jsonstore.io/6b6xxxxxxxxxxxxxxxxxxxxxxxa98";```

REPLACE THE ABOVE `endpoint` WITH YOUR OWN `endpoint`

> Regarding the `#` prefix on custom alias:
> Minimal URL is a simple URL shortener which doesn't intend on server-side logging and analytics. By serving a sub-page for each custom aliases, it creates scope for URL statistics. Please contribute to this project by making a PR.

**Comment by ghost** [comment]
Thanx again ... I will try to retheme it again to my style ...
And, regarding the endpoint, is it for anonymity or what ?! I wish to use as a real anonymous urlshortener service, and I wish u suggest me a cheap good hosting for such service :)
Besides I know ni codingso I did not understand the "PR" u mentioned.
THANX for all,

**Comment by liyasthomas** [comment]
> is it for anonymity or what ?!

Yes.

> I wish u suggest me a cheap good hosting for such service :)

There are dozens for free hosting services such as Firebase, 000webhost, herokuapp etc.. Most of them offers a free basic plan and paid extended plans. Find which one suits you the most.

> I did not understand the "PR" u mentioned.

PR = pull request.
If you'd like to contribute to any repositories, first you fork it, then you make changes, then you pull request to the original repo so he/she could review changes and merge them into master branch.

**Comment by ghost** [comment]
AHA, thanks ... I made some styling and I wish u add 3 more things :)
1. QR code :)
2. Social media FB Twitter Tumblr VK and more if u can :)
3. an option to use multi domains :)

>> I am sorry I push it too much :)

I am thinking about running mu own url shortener service, confused between paid and free options, YOURLS is so stupid interface and back en too but powerful, and then came ur  code which is simple and I like the anonymity feature :)

and how to login to dashboard in ur jasonstore ?

http://icu2.cf/m/

**Comment by liyasthomas** [comment]
Hi @mtsmayad I'm an undergraduate student, doing projects on my free time. I won't be able to dedicate anymore time or effort on mnmlurl. I intended to make a minimal URL shortener, that's how mnmlurl were born.

Please help me to pay my server bills by making a donation as much as you like, on PayPal here: https://paypal.me/liyascthomas so that I'll reconsider maintaining this project.

By the way, "JSONStore dashboard" feature is currently a work in progress.
