### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [liyasthomas/mnmlurl#108]
**jsonstore.io is down**
Since jsonstore.io is not functioning normally from many days so this shortner is not any more functional.

**To Reproduce**
1. Go to sortner website
2. paste the long link and click shorten
3. And it ever and ever struck there with status *shortening*

**Please fix it as I use it for my work**
I am an newbie and don't have much knowledge of javascript so please fix it soon using some alternatives like jsonbix.io or other such projects.

**Comment by liyasthomas** [comment]
Bug has been identified, will fix it asap.
