### ISSUE TITLE
Fork of Fossurl?

### ISSUE THREAD

**Issue by bauripalash** [liyasthomas/mnmlurl#154]
It seems this codebase is a fork of FossURL which I wrote last year. But you haven't put any mention of that and even Your `LICENSE` file still contains my name as copyright holder.

I hope you'll put a mention of FossURL.

**Comment by liyasthomas** [comment]
Wow! FINALLY. It is you. Few months back, I was browsing the internet and found a post about a url shortener. I went through it. I forked (hope it is MIT lisenced) and modified to have more features. I still didn't altered the License file. So I hope there's nothing wrong in it. 🙌🏼

The original code base is still MIT licensed to you.

**Comment by bauripalash** [comment]
I just found this on GitHub Newsletter. It's always nice to be forked, but you don't need to keep my name in the license (Still I'm not sure about that 😅)
And One thing, I was having some problems with jsonstore , so I replaced it with jsonbox. You should also check that out

**Comment by liyasthomas** [comment]
Yeah sure; I'll check it out.

And as per MIT license, I should not alter the base ownership 🙌🏼

**Comment by bauripalash** [comment]
Ah.. Okay. Thank you 😊
