### ISSUE TITLE
Is it possibile to use it on a private way?

### ISSUE THREAD

**Issue by fsgreco** [liyasthomas/mnmlurl#24]
I really love the idea of having my own url shortner but I'm a bit worried because the service remain public, so somebody I don't know could create his own url shorteners with custom alias (using my domain).

Is there any way to use it only in a private way?

**Comment by liyasthomas** [comment]
Theoretically its possible and pretty much similar to hosting on GitHub pages. Basic working is all same but there's a catch. To use it on your own private domain, you should change the `endpoint` currently served by jsonstore.io with your own private endpoint. This can be achieved by buying a custom domain and server for hosting the service.
Along with this, some security concerns will arise, such as encryption and access restrictions etc. But its all possible. Looking forward for contribution in future.

**Comment by liyasthomas** [comment]
#26 might come with a fix.
