### ISSUE TITLE
Add support for 301 redirect 

### ISSUE THREAD

**Issue by abdhass** [liyasthomas/mnmlurl#28]
**Is your feature request related to a problem? Please describe.**
It would be nice if the app can do a 301 redirect to preserve the title description image meta info on a link. Currently all links show the mnml meta info. 

**Describe the solution you'd like**
Links to be redirected via 301 instead 

**Describe alternatives you've considered**

**Additional context**
If it's a server needed, any advice? Maybe firebase cloud functions

**Comment by liyasthomas** [comment]
I afraid that feature isn't available on free endpoint services such as jsonstore.io. Will try to implement them in future development.
Watch #26 and #24 for more info.
